### ISSUE TITLE
Question : kotaのbranchの編集内容について

### ISSUE THREAD

**Issue by crab85193** [crab85193/Tely#25]
## 誰に
@KotaTamaki 

## 内容
kotaのbranchだけ、mainブランチと全く違った内容になってるんだけど...大丈夫かい？
今回の開発はDjango使ってるから、Flaskは今のところ使う予定ないんだけど、Flaskじゃないと厳しそう...？

**Comment by KotaTamaki** [comment]
内容に関してはpullして直します笑
過去にIVR実装している人のコードマネてみて仕組み理解しようとしているんだけど、Djangoでやっている人のコードがいくらやってもエラー吐かれるから、諦めてflaskの人のコードで試してみた。
pythonコード的には少ないからdjangoで書き直せるかもみてみるね

**Comment by crab85193** [comment]
@KotaTamaki 
了解です。コンフリクトには気をつけてね。
