### ISSUE TITLE
プロダクト紹介ページの作成

### ISSUE THREAD

**Issue by crab85193** [crab85193/Tely#26]
## やること
- [x] プロダクト紹介用ページのテンプレート決定
- [x] 紹介ページのTemplate作成
- [x] 紹介ページのView作成
- [x] 紹介ページのURL設定

## メモ
なし

**Comment by SuaNyan** [comment]
Templateを決定しました
→https://startbootstrap.com/previews/creative

とりあえず勉強がてらこれで紹介ページの作成を進めていきますが、他のTemplateの方が良いなど意見があったらいつでも教えてください。

**Comment by crab85193** [comment]
@SuaNyan 
可能であれば、左上にログインボタンってすぐわかるようなもの作って欲しいんだけど...
今のテンプレートでできそう？

**Comment by KotaTamaki** [comment]
@crab85193 
カニさんが作ったユーザーと管理者で見れる項目が違うってやつは別のテンプレ使っても無駄にはならない？

**Comment by SuaNyan** [comment]
@crab85193 
一応自分は、自分が選んだテンプレートの右上に四つボタンがあるから、そこにSign inとかSign upを並べて配置しようかなと思ってたんだけど、それだとわかりにくいかな...?
左上にドーンとログインボタンを配置した方がわかりやすそうだったら、 蟹さんが送ってくれたテンプレートを使ってみようかなと思う。

**Comment by crab85193** [comment]
一個一個回答するぜ

@KotaTamaki 
別のテンプレートになると、baseが違ってくるから、管理者のみ見れる項目作るには再度そこでコード組まないといけない。

@SuaNyan 
ヘッダーの項目の配色が全部一緒だから、わかりにくいなーって、ユーザー目線のカニさんが思っただけよ〜
他の人が見たらどうか分からないから、猫さんが見やすい、迷わないってやつで全然いいよ

**Comment by SuaNyan** [comment]
@crab85193 
あ〜なるほどね！確かにそうかも。
私が選んだテンプレートのど真ん中にFIND OUT MOREって書かれたでかいボタンあるんだけど、それをログイン等に使うっていうのは変かな...?

**Comment by SuaNyan** [comment]
使いづらいか〜！笑
了解、ありがとう！
とりあえず他の意見来るまでは、蟹さんの意見を踏まえて自分で考えてやってみる！

**Comment by KotaTamaki** [comment]
ログイン前のトップページでどんなアプリかわかればいいからシンプルでかっこいいのは猫さんのやつかなー
ただログイン後はいろんな機能つけていかないといけないから汎用性あるカニさんのテンプレがあってる気はする。。
ログイン前とあとはテンプレ変えても良いのかな？？

**Comment by crab85193** [comment]
認識がズレてる感じがする。
詳細は木曜日、会った日に話すわ。
猫さんはとりあえず、プロダクト紹介用のページ作成を引き続きお願いします。

**Comment by mikutoooooooo** [comment]
夜遅くにごめんね。
テンプレートをbootstrapにする理由を教えて欲しいです。
かにさんが言ってたけど、他のテンプレートだとレイアウトがスマホ表示にするとくずれるから？
bootstrapにこだわる理由がいまいちわかりません。
他に使いやすそうなツールがあったらそれ使ってもいいでしょうか？

**Comment by crab85193** [comment]
@mikutoooooooo 

移動中の回答になるから、ちゃんと答えられてなかったらごめん...

まず、Bootstrapを使う理由としては以下の理由があるよ。

- レイアウト崩れが起きない
- レスポンシブ対応が簡単
- 他の人に受け渡ししても、コードが読めない、クラスの意味がわからないと言った問題が少なくなる
- テンプレートがたくさんあるので、サイトを１から作らなくていい
- デザインが綺麗

世界的にも多く使われるぐらいにはBootstrapってとっても使いやすいと思ったから採用しました。

他に使いやすそうなツールがあっても、今のものと大きく変わるようなら、
@mikutoooooooo がbaseファイルの作成しなきゃいけないけど、大丈夫そう...？

あと、可能であれば、自分のissuesの中で質問を書いてほしい。
猫さんのやつと混ざっちゃって意味わからなくなっちゃう。
