### ISSUE TITLE
予約情報入力画面の作成

### ISSUE THREAD

**Issue by SuaNyan** [crab85193/Tely#42]
## やる事
- [x] htmlの作成
- [x] Template作成
- [x] view作成
- [x] url指定

## メモ
ユーザーが店舗、日時、人数を入力する画面の見た目を作成します。
djangoへの組み込み(Template、viewの作成とurl指定作業)は、もしかしたら誰かに質問or依頼するかもしれません。とりあえず、まず見た目部分を触ってみようと思います。

**Comment by SuaNyan** [comment]
@crab85193 
忙しい中ごめんね。質問なんだけど、もし時間があったら返信お願いしたいです。

作業の際、web上での見た目を確認しながらhtmlを作成したいと思ったので、以下のコマンドで開発用サーバーを立てて、web上での見た目を確認しながら作業しようとしました。
```py
python manage.py runserver
```
でも上記のコマンドを実行すると、環境設定が原因のエラー(環境変数の設定や、pythonのバージョン違いによるスクリプトエラーなど)がたくさん起きてしまい、その対処に手こずってしまいました。
よくよく考えたらDocker使ってたので、djangoのrunserver使うんじゃなくて、Dockerでコンテナ立てててて作業しないといけないのかもと思いました。←今ここ

docker-compose.dev.ymlファイルから開発用コンテナを立てて、それでローカルにアクセスして見るという方法が正しいのでしょうか...
いろいろ調べたんだけど、どっちが正しいのかわからなくて質問しました。

長文でわかりにくかったらごめんなさい🙇‍♀️
明日デモ会で会えると思うので、伝わらなかったら明日口頭で説明しても大丈夫です。

**Comment by crab85193** [comment]
@SuaNyan 
```
python manage.py runserver
```

これだと動きません...

今回の開発ではdockerを使用するので、コンテナを起動しないとサイト見れません...

あと、コンテナを立ち上げても、htmlファイルだけじゃサイト見れません...Viewファイルを作って、urlsを設定しなきゃいけません...

dockerに関しては、LINEのメモに書いてある手順に従ってコンテナを起動させて下さい。

Viewとurlsに関しては、dockerコンテナ起動できたら、手順書きます〜

**Comment by SuaNyan** [comment]
@crab85193 
ありがとううおおお
最初にLINEノートにDocker関連の説明書いてくれてたの、完全に忘れてた...

Dockerコンテナのビルドと起動まではできました！

お時間ある時に、Viewとurlsに関してご指導いただけたらと思います...!

**Comment by crab85193** [comment]
明日...教えられるところまででよければ教えます...

**Comment by SuaNyan** [comment]
@crab85193 お疲れ様！

ユーザーが予約情報を入力する画面の作成作業を少し進めました！
その際、urlを以下のように変更しました。

・私が作成した日時・場所・人数・店舗を入力する画面：input_reserve

・蟹さんが予め作成していた、電話番号で予約する画面：reservation→phone_reserve

アクセスに支障はないようにViewsとかurlsも変更できたので、一応報告だけしておきます！

**Comment by crab85193** [comment]
@SuaNyan 

ありがとう！！

ちなみに、余裕があれば、urlsを以下の内容で変更してほしい

- 猫さんが作成した画面 : reservation_add
  - Viewsも`class ReservationAddView` に変更
- 私が作成した、電話番号で予約する画面 : reservation_phone
  - Viewsも`class ReservationPhone`

**Comment by SuaNyan** [comment]
@crab85193 

了解！やっておきます！！🐈

**Comment by KotaTamaki** [comment]
お疲れさん
@SuaNyan 
先週話せてなかったんだけど、入力情報店舗名、日時、人数、に加えてメモ欄を追加できる？

chatgpt apiにメモ内容を踏まえてテキスト生成させたいと思ってるので

**Comment by SuaNyan** [comment]
@KotaTamaki 
お疲れー！
返信遅くなってごめんね！

了解です！次のデモ会までには完成させとくね！
