### ISSUE TITLE
お店名または場所から電話番号を取得する

### ISSUE THREAD

**Issue by KotaTamaki** [crab85193/Tely#55]
## やること
- [x] 使うサービスを選定する
- [x] 必要な項目を引数に電話番号を返すコードを作成する

## メモ
特になし

**Comment by KotaTamaki** [comment]
pythonでgoogle apiを使って店舗名から電話番号を取得するコードを作りました。
複数の場所で一致を確認済み。

それに付随して、
- 入力した店舗名をmap上での形(正規名)に変更するコード(確認画面で必要になりそう)
- 店舗名からplace_idを取得するコード(いつか使うことになるかも)
の二つ、合計３つ作成しました

@crab85193 
これらのコードはどうしておいた方がいいかな？　返信お願いします

**Comment by crab85193** [comment]
@KotaTamaki 

さすが、仕事が早い！ありがとう（土下座）

作成したコードはmanage.pyがある階層で、testって名前でディレクトリ作って、その中に置いて欲しいです！

よろしくお願いします🙏
